= About This Repository

This repository contains the TEI source file, and derived text and HTML files of an ebook posted to https://www.gutenberg.org/[Project Gutenberg]. Like the version posted to Project Gutenberg, this ebook is free from copyright in the U.S. No claim is made about its copyright status outside the U.S.

The version maintained in this repository may be slightly out-of-sync with the version maintained at Project Gutenberg. Mostly, fixes will be made first here, and only then reposted to Project Gutenberg. When you encounter any issue in this text, please report it here.

== About This Ebook

|===
|Field |Value

|Title |The Einstein Theory of Relativity
|Author |Hendrik Antoon Lorentz (1853–1928)
|Publisher |Project Gutenberg, Urbana, Illinois, USA., 2004-02-01
|Publication date |2004-02-01
|Availability |U.S. Public Domain, since published in 1920. Produced by Jeroen Hellingman and the Distributed Proofreading Team from page images provided by the Million Books Project.
|PG Ebook Number |https://www.gutenberg.org/ebooks/11335[11335]
|===
